const state = window.state = {
    cameraX: 0,
    cameraY: 0,
    logicalWidth: typeof window !== 'undefined' ? window.innerWidth : 1200,
    logicalHeight: typeof window !== 'undefined' ? window.innerHeight : 800,
    mouseX: 0,
    mouseY: 0,
    boatBob: 0,
    boatVy: 0,
    boatTilt: 0,
    boatVTilt: 0,
    boatWorldX: 0, // Set dynamically on start/resize
    rodRotation: 0,
    rodWhipVelocity: 0,
    manFacingRight: true,
    rodTip: { x: 0, y: 0 },
    msgTimer: 0,
    cycleTime: 0.5,
    pullStartX: 0,
    pullStartY: 0,
    pullCurrentX: 0,
    pullCurrentY: 0,
    hook: { x: 0, y: 0, vx: 0, vy: 0 },
    ropePoints: [],
    fishList: [],
    particles: [],
    ambientParticles: [],
    wakeParticles: [],
    hookedFish: null,
    lineTension: 0,
    slackTimer: 0,
    stars: [],
    clouds: [],
    cameraZoom: 1.0,
    playArrowWidth: 45,
    brokenHooks: [],
    isRaining: false,
    currentRainIntensity: 0,
    rainParticles: [],
    nextRainChange: 0,
    playerMoney: 0,
    playerHooks: 10,
    hookBuyQty: 1,
    overCapacityCount: 0,
    boatBroken: false,
    boatBrokenTimer: 0,
    developerZoomOverride: null,
    fishermanSpeech: "",
    fishermanSpeechTimer: 0,
    caughtFishStack: [],
    sessionCaughtLog: [],
    currentSortOption: 'newest',
    videoStream: null,
    photoModalOpen: false,
    photoFishInstance: null,
    photoFishX: 320,
    photoFishY: 240,
    photoFishRotation: 0,
    photoFishScale: 1.0,
    photoControlMode: 'move',
    lastPhotoDragPos: null,
    trackedHandPos: null,
    isDraggingPhotoFish: false,
    computedDistanceScale: 1.0,
    assignedFishLanes: [],
    assignedBirdLanes: [],
    lastPressedKey: null,
    lastReelTime: 0,
    reelEnergy: 0,
    baseReelStrength: 2.0,
    gameState: 'HOME',
    playerStats: {
        catchesCount: 0,
        escapesCount: 0,
        maxDepthReached: 0,
        rareCaught: false,
        goldAlbatross: false,
        goldLeviathan: false,
        goldTerror: false,
        goldSunray: false,
        goldTurtle: false,
        forbiddenMammalEarned: false
    },
    playerEquipment: {
        rod: 'wood_rod',
        hat: 'none',
        shirt: 'blue',
        boatColor: 'brown',
        boatType: 'wood'
    },
    ownedItems: {
        rods: ['wood_rod'],
        hats: ['none'],
        shirts: ['blue'],
        boatColors: ['brown'],
        boatTypes: ['wood'],
        supplies: []
    }
};
